ChartBoost/chartboost-mediation-ios-adapter-applovin

- Source/AppLovinAdapterConfiguration.swift
https://chartboost.atlassian.net/browse/HB-5887
https://dash.applovin.com/documentation/mediation/ios/getting-started/data-passing#location-passing
> HB-5887: add configuration setting to enable/disable AppLoving location collection

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
Adapter version '4.11.10.0.0', partner version '~> 11.10.0'
> Update Version to 4.11.10.0.0

- Source/AppLovinAdapterConfiguration.swift
https://chartboost.atlassian.net/browse/HB-5933
> HB-5933: use os_log instead of print

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
Adapter version '4.11.11.0.0', partner version '~> 11.11.0'
> Update Version to 4.11.11.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterBannerAd.swift
Adapter version '4.11.11.0.1', partner version '~> 11.11.0'
> Update Version to 4.11.11.0.1

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- README.md
- Source/AppLovinAdapter.swift
Adapter version '4.12.0.0.0', partner version '~> 12.0.0'
> Update Version to 4.12.0.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
Adapter version '4.12.1.0.0', partner version '12.1.0'
> Update Version to 4.12.1.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
Adapter version '4.12.2.0.0', partner version '~> 12.2.0'
> Update Version to 4.12.2.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterConfiguration.swift
Adapter version '4.12.3.0.0', partner version '~> 12.3.0'
> Update Version to 4.12.3.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterConfiguration.swift
Adapter version '4.12.4.0.0', partner version '~> 12.4.0'
> Update Version to 4.12.4.0.0

- ChartboostMediationAdapterAppLovin.podspec
Change podspec's spec.ios.deployment_target from 11 to 13
> HB-5850: Change iOS target version to 13

- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterAd.swift
- Source/AppLovinAdapterBannerAd.swift
- Source/AppLovinAdapterInterstitialAd.swift
- Source/AppLovinAdapterRewardedAd.swift
Applied most of the 5.0 changes in a single branch. Missing consent stuff and a few details that need discussion, to be addressed in a separate PR
> Support PartnerAdapter API 5.0 Changes

- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterBannerAd.swift
Updated implementation for removal of PartnerAdapterFormats.adaptive_banner and additiong of a BannerSize property in PartnerAdLoadRequest
> Remove PartnerAdapterFormat.adaptive_banner

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- README.md
Mediation PR: https://github.com/ChartBoost/helium-ios/pull/1785
> HB-7620: bump the Mediation SDK version to 5.0.0

- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterAd.swift
- Source/AppLovinAdapterBannerAd.swift
- Source/AppLovinAdapterInterstitialAd.swift
- Source/AppLovinAdapterRewardedAd.swift
Add support for split of PartnerAd into PartnerBannerAd and PartnerFullscreenAd
> Split PartnerAd into banner and fullscreen

- Source/AppLovinAdapter.swift
Added support for new PartnerAdapter consent APIs
> HB-7636: Consent APIs rework

- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterConfiguration.swift
Adopt new PartnerAdapterConfiguration protocol
> HB-7694: Adapter configuration rework

- Source/AppLovinAdapterBannerAd.swift
Use the pattern where we extend `BannerSize` instead of having a function that converts to the partner-specific size type.
> Use same BannerSize pattern as other adapters

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
Adapter version '4.12.5.0.0', partner version '~> 12.5.0'
> Update Version to 4.12.5.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAppLovin.podspec
- Source/AppLovinAdapter.swift
- Source/AppLovinAdapterConfiguration.swift
Adapter version '4.12.6.0.0', partner version '~> 12.6.0'
> Update Version to 4.12.6.0.0
